/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.acme.extensions

import spock.lang.Specification

class MyExtensionTest extends Specification {
    def "can call extension method"() {
        expect:
        "hello, Groovy!".taille == 14
    }
}
